### ISSUE TITLE
Wrong e2e Dockerfile configs

### ISSUE THREAD

**Issue by brogergvhs** [gmhafiz/go8#10]
Both e2e.Dockerfile and server.Dockerfile are building:

./cmd/migrate/main.go

This fails the proposed in the README command for e2e testing.

I suppose they should be building their respective files:
- server.DckerFile: ./cmd/go8/main.go
- e2e.Dockerfile: ./e2e/main.go

If this change is applied, e2e works.

**Comment by brogergvhs** [comment]
<img width="1087" alt="Screenshot 2024-11-30 at 21 57 55" src="https://github.com/user-attachments/assets/9ad2dc12-4a5d-443c-b165-6667269836b7">

These changes work, while pushing the access got denied, so can't make a pr...

**Comment by gmhafiz** [comment]
Thank you for opening this issue. Those changes looks good to me. 

To open a PR, you need to make a fork first. Commit the changes, then request a PR. You can see how github proposes to do it in here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by brogergvhs** [comment]
opened a pr :)
